version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0.0
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--api.insecure"
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager

  web1:
    image: httpd:latest
    ports:
      - 81:80
    networks:
     - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.httpd.rule=Host(`www.aprotski.tk`)"
        - "traefik.http.routers.httpd.entrypoints=web"
        - "traefik.http.services.httpd.loadbalancer.server.port=80"


  web2:
    image: httpd:latest
    ports:
      - 82:80
    networks:
     - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.httpd.rule=Host(`www.fmuela.tk`)"
        - "traefik.http.routers.httpd.entrypoints=web"
        - "traefik.http.services.httpd.loadbalancer.server.port=80"


  web3:
    image: httpd:latest
    ports:
      - 83:80
    networks:
     - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.httpd.rule=Host(`www.hyeghiazaryan.tk`)"
        - "traefik.http.routers.httpd.entrypoints=web"
        - "traefik.http.services.httpd.loadbalancer.server.port=80"

  webgeneral:
    image: httpd:latest
    ports:
      - 84:80
    networks:
     - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.httpd.rule=Host(`www.facandayk.tk`)"
        - "traefik.http.routers.httpd.entrypoints=web"
        - "traefik.http.services.httpd.loadbalancer.server.port=80"


networks:
  traefik-public:
    external: true




# docker run --name nginx_proxy -d -v `pwd`:/etc/nginx/conf.d -p 443:443 nginx

#docker run -dit -p 80:80 -p 443:443  -v $HOME/Pictures/conf:/etc/apache2/sites-enabled/ --name apacheforeground --network apacheforeground matchstic/httpd-php-ssl:latest

